### PR TITLE
Add debug Id for content assistant widgets

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Add debug Ids for content assistant widgets to simplify selenium tests work

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Review by dkulieshov — APPROVED** [review]

**Comment by SkorikSergey** [comment]
ci-test

**Comment by skryzhny** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/508/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/508//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10506)
docker image: eclipseche/che-server:10506
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by mshaposhnik** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/511/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/511//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10506)
docker image: eclipseche/che-server:10506
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by RomanNikitenko** [comment]
ci-test

**Review by vparfonov — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/517/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/517//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10506)
docker image: eclipseche/che-server:10506
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
