### PR TITLE
pageobject methods are added to createWorkspace.ts file

### PR DESCRIPTION
**Pull request by makambalaji**
### What does this PR do?
Issue Id: #21277 
pageobject methods [typeGitRepoUrl, clickOnCreateAndOpen] helps to create the and start the workspace using git repo url
typeGitRepoUrl -> This method is used to enter the git repo url in the create worksapce page
clickOnCreateAndOpen -> This methof is used to click on Create and Open button
By this 2 methods, workspace can be created using git repo url [Attached screencast for reference]

### Screenshot/screencast of this PR

Attaching the screencast for reference

https://user-images.githubusercontent.com/61005404/158768110-dc99bd46-8590-4ade-93d6-6265fa57a42f.mp4

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix or new feature ](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix-or-new-feature)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
Title looks misleading, because PR is actually adding new methods to existed page objects `Create Workspace`, not adding new one.

What issues does this PR fix or reference?

**Comment by makambalaji** [comment]
> Title looks misleading, because PR is actually adding new methods to existed page objects `Create Workspace`, not adding new one.
> 
> What issues does this PR fix or reference?

updated the issue details and attached screencast for reference

**Comment by dmytro-ndp** [comment]
@makambalaji : thank you for addressing feedback!

It's still not clear which tests new methods are for.
It would be helpful to review the usage of new methods.

**Comment by dmytro-ndp** [comment]
@makambalaji: is there dependent test run report available for review?

**Pull request closed without merging**
