### PR TITLE
Test pr to check CI.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
Test pr to check CI.

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
ci-build

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1061/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1061//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11722
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by AndrienkoAleksandr** [comment]
ci-build

**Comment by AndrienkoAleksandr** [comment]
ci-test

**Comment by AndrienkoAleksandr** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1065/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1065//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11722
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by AndrienkoAleksandr** [comment]
ci-build

**Comment by AndrienkoAleksandr** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1066/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1066//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11722
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1068/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1068//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11722
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1069/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1069//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11722
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1074/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1074//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11722
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-build

**Pull request closed without merging**
